openapi: "3.0.2"
info:
  title: Example Rest Archetype
  version: 0.0.1

paths:
  /users:
    get:
      tags:
        - Users
      summary: Gets all User
      description: Gets all users present.
      operationId: getUsers
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          minLength: 3
          maxLength: 20
        surname:
          type: string
          minLength: 3
          maxLength: 20
        username:
          type: string
          minLength: 3
          maxLength: 30
        email:
          type: string
          minLength: 3
          maxLength: 30
        address:
          type: array
          items:
            $ref: "#/components/schemas/Address"
      required:
        - name
        - surname
        - username
    Address:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
          minLength: 3
          maxLength: 20
        user:
          $ref: "#/components/schemas/User"
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message


