openapi: "3.0.2"
info:
  title: Example Rest Archetype
  version: 0.0.1

paths:
  /users:
    get:
      tags:
        - Users
      summary: Gets all User
      description: Gets all users present.
      operationId: getUsers
      x-spring-paginated: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

components:
  parameters:
    findById:
        name: id
        in: query
        description: The ID of object to be returned
        required: false
        schema:
          minimum: 0
          type: integer
          default: 0
    findByName:
        name: name
        in: query
        description: The name of object to be returned
        required: false
        schema:
          type: string
          default: "name"
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          minLength: 3
          maxLength: 20
        surname:
          type: string
          minLength: 3
          maxLength: 20
        username:
          type: string
          minLength: 3
          maxLength: 30
        email:
          type: string
          minLength: 3
          maxLength: 30
        roles:
          type: array
          items:
            $ref: "#/components/schemas/Role"
      required:
        - name
        - surname
        - username
    Role:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
          minLength: 3
          maxLength: 20
        users:
          type: array
          items:
            $ref: "#/components/schemas/User"
      required:
        - description

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message


